name: development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-verison }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          npm install

      - name: Test
        run: npm test --if-present

      - name: Push to master
        env: 
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REF=$1
          if [ -z $1 ]; then
              REF='master:refs/heads/master'
          fi

          if [ -z "${TOKEN}" ]; then
            TOKEN=${GITHUB_TOKEN}
          fi

          REMOTE_REPO="https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          cd "${GITHUB_WORKSPACE}" || exit 1
          rm -rf .git
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m 'CI Auto merge'
          git push --force $REMOTE_REPO master:$REF
